#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "cc -D_DARWIN_C_SOURCE -UOPENSSL_BN_ASM_PART_WORDS -arch arm64 -isysroot /Applications/Xcode6gmseed.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.0.sdk -Wno-unused-value -Wno-parentheses"
  #define PLATFORM "darwin-i386-cc"
  #define DATE "Wed Sep 17 15:43:15 CST 2014"
#endif
